export const SITE_CONFIG = {
  name: 'NK Velora Ventures',
  shortName: 'NKVV',
  tagline: 'Business Process Intelligence & Automation',
  philosophy: 'Diagnose → Structure → Improve → Automate → Scale',
  coreIdea: 'NKVV helps growing businesses transform complex, manual processes into structured, technology-enabled, and scalable operating systems.',
  url: 'https://nkvelora.co.in',
  location: 'Bengaluru, Karnataka, India',
  targetAudience: 'Startups, SMEs & Mid-Market Enterprises',
  emails: {
    business: 'business@nkvelora.co.in',
    founder: 'nandu@nkvelora.co.in',
    help: 'help@nkvelora.co.in',
    enquiry: 'business@nkvelora.co.in',
  },
  hero: {
    eyebrow: 'PEOPLE • PROCESS • TECHNOLOGY • AUTOMATION • SCALE',
    headline: 'Transform HR Operations. Automate the Work. Build for Scale.',
    subheadline: 'NKVV helps growing businesses transform fragmented, manual HR operations into structured, technology-enabled systems that are easier to manage, measure and scale.',
    targetAudienceNote: 'Built for founders, operations leads, and finance stakeholders transitioning from reactive work to engineered systems.',
    credibilityBar: 'Process Diagnosis • Operating Models • Labour Compliance • HR Technology • Workflow Automation',
    primaryCta: 'Connect With Us',
    secondaryCta: 'Explore Solutions',
  },
  product: {
    name: 'VELORA Compliance',
    badge: 'First Product Initiative',
    tagline: 'HR & Labour Compliance Process Diagnosis & Management',
    description: 'Diagnose compliance exposures, structure operational controls, and manage documentation with a clear roadmap toward automated compliance oversight.',
  },
  contact: {
    location: 'Bengaluru, Karnataka, India',
    primaryCta: 'Connect With Our Team',
    headline: 'Connect With Our Team',
    subheadline: "Tell us where your business operations need structure and automation. Our team will review your requirements and outline practical next steps.",
  },
  seo: {
    defaultTitle: 'NKVV — Business Process Intelligence & Automation',
    defaultDescription: 'NK Velora Ventures (NKVV) bridges process design, labour compliance, and technology automation to transform operations into scalable operating systems.',
    keywords: [
      'Business process intelligence',
      'Process automation',
      'HR process automation',
      'Labour compliance India',
      'HR compliance management',
      'Workflow automation',
      'Process diagnosis',
      'Operating model design',
      'HR operations consulting',
      'VELORA Compliance',
    ],
  },
};
